spring:
  application:
    name: web-search
  ai:
    dashscope:
      # 读取环境变量 AI_API_KEY
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: qwen-max
#          model: deepseek-r1
    nacos:
      prompt:
        template:
          enabled: true
  iqs:
    search:
      api-key: ${IQS_API_KEY}
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG