spring:
  application:
    name: function-calling
  ai:
    dashscope:
      # 读取环境变量 AI_API_KEY
      api-key: sk-45bfe78c7beb48ddb4c75fbc9d401bbb
      chat:
        options:
          model: qwen-max
    nacos:
      prompt:
        template:
          enabled: true
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG