spring:
  application:
    name: search-house
  ai:
    dashscope:
      # 读取环境变量 AI_API_KEY
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: qwen-max
    nacos:
      prompt:
        template:
          enabled: true
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG