spring:
  application:
    name: multimodality
  ai:
    dashscope:
      # 读取环境变量 AI_API_KEY
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: qwen-vl-max
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#          model: deepseek-r1
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG