services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: redis
    volumes:
      - ./conf/redis.conf:/etc/redis/redis-stand.conf
    command: redis-server /etc/redis/redis-stand.conf