spring:
  main:
    # stdio 必须配置项
    web-application-type: none
    # stdio 必须配置项
    banner-mode: off
  ai:
    mcp:
      server:
        name: weather-mcp-server
        version: 1.0.0
        type: SYNC
logging:
  pattern:
    # stdio 必须配置项
    console:
  file:
    name: mcp-weather-stdio-server.log
